#!/bin/bash
# maketable.sh: convert gc.prt into const char predefined_tables[N][2][65]
# Usage: ./maketable.sh < gc.prt > snippet.c

# Hardcoded data for private shenanigans
declare -a GAPS_DES GAPS_EAA GAPS_SEA

add_gap() {
    GAPS_DES[$1]="$2"
    GAPS_EAA[$1]="$3"
    GAPS_SEA[$1]="$4"
}

add_gap 0 "11 + Pyl (Kivenson et al. 2021)" \
  "FFLLSSSSYY*OCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG" \
  "---M------*---*----M---------------M----------------------------"

add_gap 7 "11 + Sec (toy example, biologically meaningless due to SECIS)" \
  "FFLLSSSSYY**CCUWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG" \
  "---M------**-------M---------------M----------------------------"

add_gap 8 "11 + Pyl + Sec (toy example,  biologically meaningless due to SECIS)" \
  "FFLLSSSSYY*OCCUWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG" \
  "---M------*--------M---------------M----------------------------"

add_gap 17 "Enterosoma/UBA4682 (Shulgina & Eddy 2021)" \
  "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRMVVVVAAAADDEEGGGG" \
  "---M------**--*----M---------------M----------------------------"

add_gap 18 "Peptacetobacter (Shulgina & Eddy 2021)" \
  "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRQIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG" \
  "---M------**--*----M---------------M----------------------------"

add_gap 19 "Anaerococcus, Onthovivens/UBA4855 (Shulgina & Eddy 2021)" \
  "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRWIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG" \
  "---M------**--*----M---------------M----------------------------"

add_gap 20 "Absconditabacterales (Shulgina & Eddy 2021)" \
  "FFLLSSSSYY**CCGWLLLLPPPPHHQQRRWWIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG" \
  "---M------**-----------------------M---------------M------------"

declare -a NCBI_DES NCBI_EAA NCBI_SEA
maxid=0

die_unexpected() {
  printf "Unexpected line in table given %s: %s\n" "$STATE" "$line" >&2
  exit 1
}

STATE=FILE_BEGIN
while read -r line; do
  # Remove comments crudely
  line=${line%%-- *}
  line=${line#--\**}

  # whitespace removal magic from https://stackoverflow.com/a/3352015
  line="${line#"${line%%[![:space:]]*}"}"
  line="${line%"${line##*[![:space:]]}"}"

  if [[ -z $line ]]; then
    continue  # Skip empty lines
  fi

  case $STATE in
    FILE_BEGIN)
      if [[ $line == "Genetic-code-table"* ]]; then
        STATE=TABLE_EXPECT_ELEMENT
      else
        continue
      fi
      ;;
    TABLE_EXPECT_ELEMENT)
      if [[ $line == "{" ]]; then
        STATE=ELEMENT_EXPECT_NAME
      elif [[ $line == "}" ]]; then
        STATE=TABLE_END
        break
      else
        die_unexpected
      fi
      ;;
    ELEMENT_EXPECT_NAME)
      if [[ $line == name* ]]; then
        name=${line#name \"}
        if [[ $name == *'" ,' ]]; then
          name=${name%'" ,'}
          STATE=ELEMENT_EXPECT_ID
        else
          STATE=ELEMENT_EXPECT_NAME_CONT
        fi
      else
        die_unexpected
      fi
      ;;
    ELEMENT_EXPECT_NAME_CONT)
      if [[ $line = *'" ,' ]]; then
        name=$name\ ${line%'" ,'}
        STATE=ELEMENT_EXPECT_ID
      else
        die_unexpected
      fi
      ;;
    ELEMENT_EXPECT_ID)
      if [[ $line == id* ]]; then
        id=${line#id }
        id=${id% ,}
        (( maxid = id > maxid ? id : maxid ))
        STATE=ELEMENT_EXPECT_EAA
      elif [[ $line == name* ]]; then
        continue # Skip multiple names
      else
        die_unexpected
      fi
      ;;
    ELEMENT_EXPECT_EAA)
      if [[ $line == 'ncbieaa  "'* ]]; then
        eaa=${line#'ncbieaa  "'}
        eaa=${eaa%\",}
        STATE=ELEMENT_EXPECT_SEA
      else
        die_unexpected
      fi
      ;;
    ELEMENT_EXPECT_SEA)
      if [[ $line == 'sncbieaa "'* ]]; then
        sea=${line#'sncbieaa "'}
        sea=${sea%\"}
        STATE=ELEMENT_EXPECT_END
      else
        die_unexpected
      fi
      ;;
    ELEMENT_EXPECT_END)
      if [[ $line == "} ," || $line == "}," ]]; then
        NCBI_DES[$id]=$name
        NCBI_EAA[$id]=$eaa
        NCBI_SEA[$id]=$sea
        STATE=TABLE_EXPECT_ELEMENT
      elif [[ $line == "}" ]]; then
        NCBI_DES[$id]=$name
        NCBI_EAA[$id]=$eaa
        NCBI_SEA[$id]=$sea
        STATE=TABLE_END
        break
      else
        die_unexpected
      fi
      ;;
    TABLE_END)
      if [[ $line == "}" ]]; then
        STATE=FILE_END
      else
        die_unexpected
      fi
      ;;
    FILE_END)
      ;;
  esac
done

# Make sure initialization only happens at ATG, GTG, TTG
SEAREF="---M---------------M---------------M----------------------------"
mask_sea() {
  local oldsea=$1 newsea
  for i in {0..63}; do
    if [[ ${oldsea:i:1} != '*' && ${oldsea:i:1} != '-' ]]; then
      newsea+=${SEAREF:i:1}
    else
      newsea+=${oldsea:i:1}
    fi
  done
  echo "$newsea"
}

printf "// Generated by maketable.sh\n"
printf "const char predefined_tables[%d][2][65] = {\n" "$((maxid + 1))"

for (( i=0; i<=maxid; i++ )); do
  if [[ -n ${NCBI_DES[$i]} ]]; then
    if [[ -n ${GAPS_DES[$i]} ]]; then
      printf 'Warning: Both NCBI and GAPS entries for id %d, using NCBI\n' "$i" >&2
    fi
  else
    if [[ -n ${GAPS_DES[$i]} ]]; then
      NCBI_DES[$i]="(NON-NCBI) "${GAPS_DES[$i]}
      NCBI_EAA[$i]=${GAPS_EAA[$i]}
      NCBI_SEA[$i]=${GAPS_SEA[$i]}
    else
      NCBI_DES[$i]="(NON-NCBI) Undefined, fill with standard"
      NCBI_EAA[$i]="FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG"
      NCBI_SEA[$i]="---M------**--*----M---------------M----------------------------"
    fi
  fi
  printf '  /* %d. %s */\n  {\n    "%s",\n    "%s"\n  },\n' "$i" "${NCBI_DES[$i]}" "${NCBI_EAA[$i]}" "$(mask_sea "${NCBI_SEA[$i]}")"
done

printf '};\n'
