/* Generated by maketable.sh */
const char predefined_tables[34][2][65] = {
  /* 0. (NON-NCBI) 11 + Pyl (Kivenson et al. 2021) */
  {
    "FFLLSSSSYY*OCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------*---*----M---------------M----------------------------"
  },
  /* 1. Standard */
  {
    "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------**--*----M---------------M----------------------------"
  },
  /* 2. Vertebrate Mitochondrial */
  {
    "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSS**VVVVAAAADDEEGGGG",
    "----------**-----------------------M----------**----------------"
  },
  /* 3. Yeast Mitochondrial */
  {
    "FFLLSSSSYY**CCWWTTTTPPPPHHQQRRRRIIMMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "----------**-----------------------M----------------------------"
  },
  /* 4. Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma */
  {
    "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------**-------M---------------M----------------------------"
  },
  /* 5. Invertebrate Mitochondrial */
  {
    "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG",
    "---M------**-----------------------M----------------------------"
  },
  /* 6. Ciliate Nuclear; Dasycladacean Nuclear; Hexamita Nuclear */
  {
    "FFLLSSSSYYQQCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "--------------*--------------------M----------------------------"
  },
  /* 7. (NON-NCBI) Unused - DO NOT USE */
  {
    "***M***************M***************M****************************",
    "***M***************M***************M****************************"
  },
  /* 8. (NON-NCBI) Unused - DO NOT USE */
  {
    "***M***************M***************M****************************",
    "***M***************M***************M****************************"
  },
  /* 9. Echinoderm Mitochondrial; Flatworm Mitochondrial */
  {
    "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNNKSSSSVVVVAAAADDEEGGGG",
    "----------**-----------------------M----------------------------"
  },
  /* 10. Euplotid Nuclear */
  {
    "FFLLSSSSYY**CCCWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "----------**-----------------------M----------------------------"
  },
  /* 11. Bacterial, Archaeal and Plant Plastid */
  {
    "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------**--*----M---------------M----------------------------"
  },
  /* 12. Alternative Yeast Nuclear */
  {
    "FFLLSSSSYY**CC*WLLLSPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "----------**--*----M---------------M----------------------------"
  },
  /* 13. Ascidian Mitochondrial */
  {
    "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSGGVVVVAAAADDEEGGGG",
    "---M------**-----------------------M----------------------------"
  },
  /* 14. Alternative Flatworm Mitochondrial */
  {
    "FFLLSSSSYYY*CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNNKSSSSVVVVAAAADDEEGGGG",
    "-----------*-----------------------M----------------------------"
  },
  /* 15. Blepharisma Macronuclear */
  {
    "FFLLSSSSYY*QCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "----------*---*--------------------M----------------------------"
  },
  /* 16. Chlorophycean Mitochondrial */
  {
    "FFLLSSSSYY*LCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "----------*---*--------------------M----------------------------"
  },
  /* 17. (NON-NCBI) Enterosoma/UBA4682 (Shulgina & Eddy 2021) */
  {
    "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRMVVVVAAAADDEEGGGG",
    "---M------**--*----M---------------M----------------------------"
  },
  /* 18. (NON-NCBI) Peptacetobacter (Shulgina & Eddy 2021) */
  {
    "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRQIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------**--*----M---------------M----------------------------"
  },
  /* 19. (NON-NCBI) Anaerococcus, Onthovivens/UBA4855 (Shulgina & Eddy 2021) */
  {
    "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRWIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------**--*----M---------------M----------------------------"
  },
  /* 20. (NON-NCBI) Absconditabacterales (Shulgina & Eddy 2021) */
  {
    "FFLLSSSSYY**CCGWLLLLPPPPHHQQRRWWIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------**-----------------------M----------------------------"
  },
  /* 21. Trematode Mitochondrial */
  {
    "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNNKSSSSVVVVAAAADDEEGGGG",
    "----------**-----------------------M----------------------------"
  },
  /* 22. Scenedesmus obliquus Mitochondrial */
  {
    "FFLLSS*SYY*LCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "------*---*---*--------------------M----------------------------"
  },
  /* 23. Thraustochytrium Mitochondrial */
  {
    "FF*LSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "--*-------**--*--------------------M----------------------------"
  },
  /* 24. Rhabdopleuridae Mitochondrial */
  {
    "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSSKVVVVAAAADDEEGGGG",
    "---M------**-------M---------------M----------------------------"
  },
  /* 25. Candidate Division SR1 and Gracilibacteria */
  {
    "FFLLSSSSYY**CCGWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------**-----------------------M----------------------------"
  },
  /* 26. Pachysolen tannophilus Nuclear */
  {
    "FFLLSSSSYY**CC*WLLLAPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "----------**--*----M---------------M----------------------------"
  },
  /* 27. Karyorelict Nuclear */
  {
    "FFLLSSSSYYQQCCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "--------------*--------------------M----------------------------"
  },
  /* 28. Condylostoma Nuclear */
  {
    "FFLLSSSSYYQQCCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "----------**--*--------------------M----------------------------"
  },
  /* 29. Mesodinium Nuclear */
  {
    "FFLLSSSSYYYYCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "--------------*--------------------M----------------------------"
  },
  /* 30. Peritrich Nuclear */
  {
    "FFLLSSSSYYEECC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "--------------*--------------------M----------------------------"
  },
  /* 31. Blastocrithidia Nuclear */
  {
    "FFLLSSSSYYEECCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "----------**-----------------------M----------------------------"
  },
  /* 32. Balanophoraceae Plastid */
  {
    "FFLLSSSSYY*WCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG",
    "---M------*---*----M---------------M----------------------------"
  },
  /* 33. Cephalodiscidae Mitochondrial */
  {
    "FFLLSSSSYYY*CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSSKVVVVAAAADDEEGGGG",
    "---M-------*-------M---------------M----------------------------"
  },
};
